<?php include "../../pagExtras/DatabaseConnection.php" ?>
<?php 
	/*--------------------------------------------------Inserir dados paciente -------------------------------------*/
include('processosForm.php');
$query = "INSERT INTO `paciente`(
`pac_nome`,             
`pac_sobrenome`, 	
`pac_rg`, 
`pac_CPF`, 
`pac_dt_nasc`, 
`pac_est_civil`, 
`pac_religiao`, 
`pac_dt_entrada`, 
`pac_sexo`, 
`pac_etnia`, 
`pac_peso`, 
`pac_alt`, 
`pac_status`,
`pac_enc`,
`pac_chegada`, 
`pac_dep`, 
`pac_vicio`, 
`pac_hipertenso`, 
`pac_diabete`, 
`pac_cirurgia`, 
`pac_ulcera`, 
`pac_ulceraEst`, 
`pac_crise_con`, 
`pac_medicamento`, 
`pac_alergia_med`,
`pac_chegadaDesc`,
`pac_vicioDesc`,
`pac_cirurgiaDesc`,
`pac_medicamentoDesc`,
`pac_alergiaDesc`) VALUES (
'".$nome."',
'".$sobrenome."',
'".$RG."',
'".$CPF."',
'".$data."',
'".$estadoCivil."',
'".$religiao."',
'".$dataEntrada."',
'".$sexo."',
'".$etnia."',
'".$peso."',
'".$altura."','Ativo',
'".$encaminhamento."',
'".$condicaoChegada."',
'".$grauDependencia."',
'".$vicio."',
'".$hipertenso."',
'".$diabetico."',
'".$cirurgia."',
'".$ulcera."',
'".$estagioUlc."',
'".$criseConv."',
'".$usaMedicamento."',
'".$alergiaMedicamento."',
'".$descCheg."',
'".$descVicio."',
'".$descCiru."',
'".$descMed."',
'".$descAlergia."')";

mysqli_query($con, $query);
	/*--------------------------------------------------Inserir dados paciente -------------------------------------*/
?>